import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joseph Acevedo | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Hero />
      </main>

      <footer></footer>
    </div>
  );
}
